### ISSUE TITLE
Questions about Field Maps

### ISSUE THREAD

**Issue by Govish** [shimming-toolbox/susceptibility-to-fieldmap-fft#20]
Hi All!
This is Ishaan from Martinos--I have a couple questions about the field maps you guys recently sent over:

- What are the units of the field map? The data seems to go from -10 to +8
- What's the field strength that this map was "acquired" at?
- Are the maps phase-unwrapped?
- Is it possible to also have the magnitude information from these maps (or some other means of generating a mask)? (RESOLVED - Charles sending over the mask data)

Thanks!

**Comment by CharlesPageot** [comment]
Hi Ishaan!

Here are some answers for your questions.

### What are the units of the field map? The data seems to go from -10 to +8

The field maps units are in ppm and they are normalized by field strength. 

### What's the field strength that this map was "acquired" at?

Since the field maps have normalized units, users need to adjust it depending on their needs. Values in Tesla or in Hz can easily be retrieved by multiplying the whole field map by $B_0 \cdot 10^{-6}$ or $\gamma \cdot B_0 \cdot 10^{-6}$ respectively.

- Ex. for a field map in Tesla at 3T:    **3D_fieldmap_array** $\cdot$ $(3\cdot 10^{-6})$
- Ex. for a frequency map at 7T:    **3D_fieldmap_array** $\cdot$ $(\gamma\cdot7\cdot 10^{-6})$

### Are the maps phase-unwrapped?

The method used simulates directly the $B_0$ variation in the $z$ direction. There was no need to perform phase-unwrapping, as is typically done for experimentally acquired field maps. For more information about how the simulation works, I invite checking the [README.md](https://github.com/shimming-toolbox/susceptibility-to-fieldmap-fft/blob/main/README.md).


Let me know if something is not clear! @Govish
